layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Kubernetes
    web_url: https://kubernetes.io/
    image_url: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
    
  - name: Prometheus  
    web_url: https://prometheus.io/
    image_url: https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Prometheus_software_logo.svg/1033px-Prometheus_software_logo.svg.png
